FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

LABEL maintainer='UNISOUND NNI Team<xieyuandong@unisound.com>'

RUN DEBIAN_FRONTEND=noninteractive && \
    apt-get -y update && \
    apt-get -y install sudo \
    apt-utils \
    git \
    curl \
    vim \
    unzip \
    wget \
    build-essential \ 
    cmake \
    libopenblas-dev \
    automake \
    openssh-client \
    openssh-server \
    lsof \
    python3.5 \
    python3-dev \
    python3-pip \
    python3-tk \
    libcupti-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

#
# update pip
#
RUN python3 -m pip install --upgrade pip

# numpy 1.14.3  scipy 1.1.0 
RUN python3 -m pip --no-cache-dir install \
    numpy==1.14.3 scipy==1.1.0 

#
# Tensorflow 1.10.0
#
RUN python3 -m pip --no-cache-dir install tensorflow-gpu==1.10.0

#
# Keras 2.1.6
#
RUN python3 -m pip --no-cache-dir install Keras==2.1.6

#
# PyTorch 
#
RUN python3 -m pip --no-cache-dir install torch==0.4.1
RUN python3 -m pip install torchvision==0.2.1

#
# sklearn 0.20.0
#
RUN python3 -m pip --no-cache-dir install scikit-learn==0.20.0

#
# pandas==0.23.4 lightgbm==2.2.2
#
RUN python3 -m pip --no-cache-dir install pandas==0.23.4 lightgbm==2.2.2

#
# Compile nni
#
WORKDIR /nni/
COPY . /nni/

RUN make install-dependencies
RUN make build && make dev-install
EXPOSE 8080
ENV PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/root/.local/bin:/usr/bin:/bin:/sbin
ENTRYPOINT ["/bin/bash"]
